### ISSUE TITLE
Remove peerDependencies

### ISSUE THREAD

**Issue by monolithed** [pghalliday/grunt-mocha-test#100]
```
npm WARN peerDependencies The peer dependency mocha@>=1.20.0 included from grunt-mocha-test will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

In short, peerDependencies should probably be removed:
See for context: npm/npm#6565

**Comment by pghalliday** [comment]
I'm not sure I need to remove the peerDependency - it's true that in future they will not be installed automatically but it's still useful to know that there are dependencies. Also it makes no sense to depend on mocha explicitly as then I would be back in the daft situation of releasing this everytime mocha updated.

My understanding of that warning is just that I should be aware that the dependency won't be installed and I'm fine with that. I'm hoping it will still do version checks and emit warnings/errors when required peer dependencies are not present

**Comment by monolithed** [comment]
@pghalliday, my mistake.

**Comment by pghalliday** [comment]
np
