### ISSUE TITLE
Passing Mocha arguments

### ISSUE THREAD

**Issue by r3mus** [pghalliday/grunt-mocha-test#109]
Is there a way to pass mocha arguments when running inside Grunt?

E.g.:

    mochaTest: {
        test: {
            src: ['tests/main.test.js'],
        }
    }

Works just fine, but I'd like to do:

    mochaTest: {
        test: {
            src: ['tests/main.test.js', '--bail'],
        }
    }

But that obviously doesn't work.

**Comment by pghalliday** [comment]
Only those supported by the API which can be passed through options. The plugin doesn't shell out to Mocha.

I think bail is supported, haven't tried it though.

```javascript
mochaTest: {
  test: {
    options: {
      bail: true
    },
    src: ['tests/main.test.js'],
  }
}
```

FYI, API options are in the Mocha source here: https://github.com/mochajs/mocha/blob/master/lib/mocha.js#L56

**Comment by pghalliday** [comment]
I assume this answered the question - closing
