### ISSUE TITLE
Unable to run the suites twice (simple case)

### ISSUE THREAD

**Issue by ekkis** [pghalliday/grunt-mocha-test#112]
I've read through: https://github.com/pghalliday/grunt-mocha-test/issues/108 but I think I have a simpler case where this fails.  here's my (abridged) `Gruntfile.js`:

```javascript
  1 module.exports = function(grunt) {
  2     'use strict';
  3     require('load-grunt-tasks')(grunt);
  4     grunt.initConfig({
 24         watch: {
 25             node: {
 26                 files: ['src/*.js', 'test/*-node.js'],
 28                 tasks: ['mochaTest'],
 29                 options: { spawn: false }
 30             },
 36         },
 43         mochaTest: {
 44             src: ['test/*-node.js']
 45         },
102     });
103 
104     var changedFiles = Object.create(null);
105     var onChange = grunt.util._.debounce(function() {
106         grunt.config('jshint.all.src', Object.keys(changedFiles));
107         changedFiles = Object.create(null);
108     }, 200);
109     grunt.event.on('watch', function(action, filepath) {
110         changedFiles[filepath] = action;
111         onChange();
112     });
113 
115     grunt.registerTask('test', ['watch']);
116 };
```

and by way of explanation, the `spawn: false` is there for the `grunt.event.on()`, which makes sure to run jshint only on files that have changed (config not shown).

what happens is the first time I save a file my tests run fine but the second time they don't.  here's some (abridged) output:

> aprilis:client-side-testing ekkis$ grunt test
> Running "watch" task
> Waiting...
> >> File "test/html-node.js" changed.
>
> Running "mochaTest:src" (mochaTest) task
>
>   HTML string functions
>     Icon
>       ✓ simple
>     New target
>       ✓ simple
>     tag
>       ✓ simple
>
>   String functions
>     ✓ Stars
>     Quoting
>       ✓ supports enclosing
>     toTitleCase
>       ✓ empty
>       ✓ single word>     spaced text to camel case
>       ✓ empty
>       ✓ multiple
>
>   Utility functions
>     Objects
>       set
>         ✓ basic
>       ext
>         ✓ basic
>     Arrays
>       unique
>         ✓ basic
>       obj
>         ✓ key/value arrays
>
>   67 passing (31ms)
>
>
> Running "watch" task
> Completed in 0.251s at Wed Dec 30 2015 14:45:00 GMT-0800 (PST) - Waiting...
> >> File "test/html-node.js" changed.
>
> Running "mochaTest:src" (mochaTest) task
>
>
>   **0 passing (0ms)**
>
>
> Running "watch" task
> Completed in 0.034s at Wed Dec 30 2015 14:45:12 GMT-0800 (PST) - Waiting...
>
>   [Återskapat 30 dec. 2015 14:47:09]
> Last login: Wed Dec 30 14:47:02 on console

where it's clear that the second run failed **0 passing (0ms)**.  is it my bad, did I miss something? or could it be the same underlying cause as the other issue?

**Comment by pghalliday** [comment]
Can you use the `clearRequireCache` option?
That will allow `mocha` to reload the tests.

The use of `watch` without `spawn` is a well known problem due to the way `mocha` works - it loads tests by using `require` but then if you try to create a second `mocha` instance in the same process with the same test files it just hits the require cache and the tests are not added.

I have been considering some solutions to #108 that would reuse the same `mocha` instance in some cases, but honestly this isn't high on my list of things to tackle.

My recommendation is still to never use `spawn: false` with watch and `grunt-mocha-test` - I don't know why you need to though

**Comment by ekkis** [comment]
hmm... the `clearRequireCache` certainly seems like what I would need (according to the docs since I'm not spawning in watch)

    42         mochaTest: {
    43             options: {
    44                 clearRequireCache: true
    45             },  
    46             src: ['test/*-node.js']
    47         },  

but curiously when I use it browserification breaks and my tests won't run:

> Running "remove:default_options" (remove) task
>
> Running "browserify:libs" (browserify) task
> Warning: Cannot read property 'defaultEncoding' of undefined Use --force to continue.
> 
> Aborted due to warnings.

here's the definition for that section:

    14         browserify: {
    15             libs: {
    16                 src: ['src/*.js'],
    17                 dest: 'test/libs.js'
    18             },  
    19             tests: {
    20                 src: ['test/*-web.js'],
    21                 dest: 'test/tests.js'
    22             }   
    23         },  

I can't understand how one affects the other... thoughts?

**Comment by ekkis** [comment]
> My recommendation is still to never use spawn: false with watch and grunt-mocha-test - I don't know why you need to though

the `grunt.event.on()` at line 109 requires that new mocha instances not be spawned to work.  and the reason I have it is that it performs `jshint` checks on only the files that have changed (as opposed to on all the files).  if ultimately I can't get this to work I can turn spawning back on and just lint all the files with every run.  sub-optimal but frankly this stuff is so complicated I just want to get something to work

**Comment by pghalliday** [comment]
`clearRequireCache` is a sledgehammer and certainly not guaranteed to work with other libraries. The most common problem I have encountered is that a library gets loaded twice when it doesn't expect to. TBH I don't know what the issue would be with Browserify but if you figure it out, I would be interested

**Comment by ekkis** [comment]
what I don't understand is: `clearRequiredCache` is an option to `mochaTest`, which runs only after browserify has run.  so I don't see how turning this option on could affect browserify at all.  if you want to see the whole Gruntfile, see: http://termbin.com/2avo

**Comment by ekkis** [comment]
one other thought: the grunt `test` task is defined so as to run the node tests first 'mochaTest' and then browserify and run tests under the phantom browser.  just for kicks I changed the order to this: 

```
grunt.registerTask('test', [
    'jshint', 'remove', 'browserify', 'mochaTest', 'karma:phantom'
]);
```

and that seems to work.  curious no? it means that mochaTest is doing something to the environment

**Comment by pghalliday** [comment]
I'll be honest, I have no clue what could be causing the problem - my only recommendation is to turn off `clearRequireCache` and turn on `spawn`. Beyond that I can't see much wrong with the gruntfile you linked.

**Comment by pghalliday** [comment]
btw, I reproduced the issue with `browserify` and `clearRequireCache` but don't really see it as a problem I want to solve in `grunt-mocha-test`. It will only complicate things and trying to be compatible with everything in this way is a can of worms I don't really want to open - if you find a sensible generic solution though, pull requests are welcome :)

**Comment by ekkis** [comment]
hmm... regardless of where it gets solved, it's important to understand how it happens, i guess primarily, to determine culpability.  some piece of software needs to be changed.  did you figure out why this happens?

**Comment by pghalliday** [comment]
not sure i agree - works fine if you use `spawn` and turn off `clearRequireCache`. Archecturally I would say the problem is in Mocha itself due to the way it uses require to load tests - which is affected by the behaviour of the require cache - which in turn was never intened to be used in the way Mocha uses it. However I doubt that will change and this corner case is not worth the effort/complexity to work around in my opinion.

So when you ask if I figured out why it happens - I knew exactly why it happened before you asked because this comes up frequently when watch is used without spwan. With regard to `browserify` and clearRequire Cache I'm not very interested as that is just a hack for people who insist on not using spawn and I'm not warrantying it.

If you feel that that hack can be improved then have a go and submit a pull request. Remember to add tests...
