### ISSUE TITLE
For loop adds random style names when iterating over a string

### ISSUE THREAD

**Issue by making3** [pghalliday/grunt-mocha-test#114]
Hi, 

Before I get into the details, I have ran these tests using grunt-simple-mocha, grunt-execute, and mocha directly, however, grunt-mocha-test and grunt-simple-mocha are the only ones that produce this result, so I may be incorrect on which project this belongs in.

OS: Windows 7 64 bit
Node: 5.1.0
Grunt-cli: 0.1.13
Mocha: 2.3.4

When I run a simple `for (var i in string)` loop, it causes additional properties to be added to the variable `i`. For example:

    var message = 'asdf';
    
    for (var i in message) {
        console.log('i: ', i);
    }
    // i: 0, 1, 2, 3, bold, underline, strikethrough, ....

Normally the result of the console logs should be:
 
    // i: 0 [a], 1 [s], 2 [d], 3 [f]

That's it. Below is the files I have tested with in a fresh project.

test.js:

	var message = 'asdf';

	for (var i in message) {
		console.log('i: ', i);
	}

test\example.test.js:

	describe('example', function () {
		it('should loop through a string', function (done) {
			var message = 'asdf';

			for (var i in message) {
				console.log('i: ', i);

				if (isNaN(i)) {
					done('not a number'); // Breaks in grunt-mocha-test & grunt-simple-mocha, but not "mocha test\example.test.js"
					return;
				}
			}

			done();
		});
	});

Gruntfile.js:

	module.exports = function (grunt) {
		grunt.initConfig({
			pkg: grunt.file.readJSON('package.json'),
			mochaTest: {
				all: {
					options: {
						require: [ 'should' ],
					},
					src: [ 'test/example.test.js']
				}
			},
			simplemocha: {
				all: {
					options: {
						require: [ 'should' ],
					},
					src: [ 'test.js' ] // for demonstration purposes
				}
			},
			execute: {
				target: {
					src: 'test.js'
				}
			}
		});

		grunt.loadNpmTasks('grunt-mocha-test');
		grunt.loadNpmTasks('grunt-simple-mocha');
		grunt.loadNpmTasks('grunt-execute');

		grunt.registerTask('default', [ 'mochaTest' ]);
		grunt.registerTask('mocha-test', 'mochaTest');
		grunt.registerTask('mocha', 'simplemocha');
		grunt.registerTask('ex', 'execute');
	};

[Screenshot to console image](http://i.imgur.com/JizHkT5.png)

I ended up using `for (var i = 0; i < message.length; i++)` for my actual code, but I figured I would report the issue. Let me know if you need any further information. Feel free to close this if this isn't the correct project that's causing this.

**Comment by pghalliday** [comment]
can't see how `grunt-mocha-test` could cause this, wonder if it's something grunt does :s

**Comment by pghalliday** [comment]
Yup I just created this `Gruntfile.js`

```
module.exports = function(grunt) {
  var message = 'asdf';

  for (var i in message) {
      console.log('i: ', i);
  }
};
```

And got this output:

```
i:  0
i:  1
i:  2
i:  3
i:  bold
i:  underline
i:  strikethrough
i:  italic
i:  inverse
i:  grey
i:  black
i:  yellow
i:  red
i:  green
i:  blue
i:  white
i:  cyan
i:  magenta
i:  greyBG
i:  blackBG
i:  yellowBG
i:  redBG
i:  greenBG
i:  blueBG
i:  whiteBG
i:  cyanBG
i:  magentaBG
i:  rainbow
i:  zebra
i:  stripColors
i:  zalgo
```

**Comment by making3** [comment]
@pghalliday, that would be correct. I just redid this on my home computer using that in the Gruntfile alone, with fresh node (4.2.4), grunt, and mocha. I'll open an issue on the Grunt repo instead, thanks.
