### ISSUE TITLE
Ability to specify path for mocha.opts

### ISSUE THREAD

**Issue by justinhelmer** [pghalliday/grunt-mocha-test#115]
First, thanks for the great tool. It has proven incredibly useful in our `grunt` workflow.

My question is with respect to `mocha.opts`. In an effort _not_ to maintain options in two places, it would be ideal in our scenario to take advantage of `mocha.opts`. However, because of our complicated directory structure, the `mocha.opts` file does not sit in the default `./test/mocha.opts` location.

With the `CLI`, the `--opts` path can be provided, i.e.:

```bash
./node_modules/mocha/bin/mocha ./webserver/test/rspec --opts ./webserver/test/mocha.opts
```

Is there a way to provide this path option to the `grunt.config`? I have tried all of the following:

```js
config.mochaTest = {
  options: {
    opts: 'webserver/test/mocha.opts'
  },
  target: {...}
};

//----------------------//

config.mochaTest = {
  target: {
    options: {
      opts: 'webserver/test/mocha.opts'
    },
    src: [...]
  }
};

//----------------------//
config.mochaTest = {
  target: {...}
};

config.mochaTestConfig = {
  options: {
    opts: 'webserver/test/mocha.opts'
  },
};
```

Any help would be greatly appreciated.

**Comment by pghalliday** [comment]
I don't think it's possible using the Mocha API, options are only loaded from a file in the CLI interface.

This is how it does it by just turning the file into command line options:

https://github.com/mochajs/mocha/blob/master/bin/options.js

Are you trying to use Mocha both directly and via grunt?

If you're just using grunt and have lots of test tasks or maybe multiple gruntfiles then you could use variables or a js module that you require and includes the options

**Comment by justinhelmer** [comment]
I appreciate the quick reply.

In this particular context, we need to use mocha both within `grunt` and outside of it. Won't always be JS, although I appreciate the suggestions.
