### ISSUE TITLE
How to use report options 

### ISSUE THREAD

**Issue by nchejara** [pghalliday/grunt-mocha-test#119]
Hi
I am using 'mochawesome' html report for automation and this custom reports come with several reports options - such as

 --reporter-options reportDir="server-report",reportName="automation-report",reportTitle="Server API Automation"

Can anyone help me how to use report options!

**Comment by pghalliday** [comment]
I think you can just add them to the options block, with those names

**Comment by ericmacfa** [comment]
You may have figured this out by now, but for other people's benefit:

From the [mochawesome docs](https://github.com/adamgruber/mochawesome#options) you would have to set the mochaTest config in your GruntFile as follows (using your own environment name of course):

```
mochaTest: {
    yourEnvironmentName: {
        reporter: 'mochawesome',
        reporterOptions: {
            reportDir: 'server-report',
            reportName: 'automation-report',
            reportTitle: 'Server API Automation'
        }
    }
}
```

**Comment by pghalliday** [comment]
thanks
