### ISSUE TITLE
Node 5 issue

### ISSUE THREAD

**Issue by outaTiME** [pghalliday/grunt-mocha-test#121]
Hi, mocha test doesn't work with node 5, check out the travis output:

<img width="1013" alt="screen shot 2016-04-19 at 2 21 11 pm" src="https://cloud.githubusercontent.com/assets/140472/14648731/1e0a16e4-063a-11e6-88a6-19545c2d4b3c.png">

look the WARN:

```
npm WARN grunt-mocha-test@0.12.7 requires a peer of mocha@>=1.20.0 but none was installed.
```

any advise with that ??

thks !!

**Comment by outaTiME** [comment]
btw, works awesome in other builds ...

<img width="1014" alt="screen shot 2016-04-19 at 2 23 53 pm" src="https://cloud.githubusercontent.com/assets/140472/14648788/61991b26-063a-11e6-8206-6efd705943c7.png">

**Comment by pghalliday** [comment]
You need to install mocha, ie. add it to your `devDependencies`. NPM no longer installs peer dependencies for you automatically, hence the warning
