### ISSUE TITLE
Allow to run a single test file

### ISSUE THREAD

**Issue by jaimeschettini** [pghalliday/grunt-mocha-test#123]
Hello, 

It would be nice if we could run a single test file instead of the whole suite. This is useful during development mainly when you have hundreds of tests or when your tests take sometime to be run, and you are creating a new test (or while doing TDD), because at this stage, you fail tests a lot, and your test get lost in console, among the others.

So, you could add a option so we can override the 'src' option.
For example, in my project this option is like this:
src: ['test/**/*.js']

But if I want to run a single test, I could run grunt like this:
grunt test my-single-test-path.js

**Comment by pghalliday** [comment]
Not sure what the best way to tackle this would be. After all this would be more in the grunt realm than the plugin realm. You may be able to achieve this in your gruntfile without changes to the plugin. Maybe a new task that sets its src from a cli option

**Comment by jaimeschettini** [comment]
Thanks, I'll try something like you said.

**Comment by sateffen** [comment]
Like @pghalliday said, here a simple example:

```
mochaTest: {
  run: {
    src: grunt.option('only') ? [grunt.option('only')] : ['test/**/*.spec.js']
  }
}
```

Then you can call *grunt mochaTest:run --only test/only-this.spec.js*.

**Comment by jaimeschettini** [comment]
Thanks for the example!

**Comment by pjvds** [comment]
This issue can be closed @pghalliday explained why and @sateffen gave an perfectly working example on how to achieve this.

**Comment by pghalliday** [comment]
okey doke, closing :)
