### ISSUE TITLE
Always return zero exit code if force: true is in options 

### ISSUE THREAD

**Issue by ngeor** [pghalliday/grunt-mocha-test#124]
When using this plugin in Bamboo, you have to add two steps:
- run the tests (grunt task)
- collect the test results (Bamboo feature)

If exit code is not zero, Bamboo reports it as testless build. The workaround is to add '--force' in the grunt command line. Then Bamboo can collect the report and provide the details of the exact test that failed.

It would be great if I could avoid the '--force' command line option. I would prefer to configure inside mochaTest that it should run in 'force' mode. This way, I can run something like 'grunt ci' (a larger alias that encompasses many tasks) without --force.

**Comment by pghalliday** [comment]
you could use this plugin to force grunt to continue with more control

https://www.npmjs.com/package/grunt-continue

**Comment by ianwremmel** [comment]
I'm actually asking the mocha maintainers for a similar thing. force and grunt-continue both lump test failures and test runner failures into the same category and, from my point of view, a failed test is a success if my test runner generates e.g. a junit file to that effect.
