### ISSUE TITLE
it.only and describe.only don't work with mocha 3 (they work when running mocha directly, not via grunt-mocha)

### ISSUE THREAD

**Issue by ohjames** [pghalliday/grunt-mocha-test#127]
They work if I run mocha manually, when run via grunt-mocha it's as if there was no `.only` anywhere.

**Comment by ohjames** [comment]
It was working in `grunt-mocha-test` version `0.10.2` but is broken in `0.12.7`.

**Comment by ohjames** [comment]
If I install `mocha 2` alongside `0.12.7` then `.only` works, it only breaks when I'm using `mocha 3` alongside `0.12.7`... so I guess something about the API or the options has changed.

**Comment by pghalliday** [comment]
Working on a fix - see my comment on https://github.com/mochajs/mocha/issues/2430

**Comment by pghalliday** [comment]
Should be working now in version 0.13.0 (upped the minor version in case this breaks compatibility with earlier versions of Mocha)

**Comment by pghalliday** [comment]
Refactored in 0.13.2 to use the mocha API as documented. Mocha seems to have stopped leaking unhandled exceptions asynchronously which is nice as it means my workaround is no longer needed (fingers crossed)
