### ISSUE TITLE
Error - Cannot find module 'coverage/blanket'

### ISSUE THREAD

**Issue by gabaum10** [pghalliday/grunt-mocha-test#128]
I am trying to get the coverage working with the blanket integration based on the example in the docs.  No matter what I do I can't get it to work.  I've done the npm install for blanket, so I know that's there.

This is what my grunt task looks like:

`
mochaTest: {
            test: {
                options: {
                    reporter: 'spec',
                    timeout: 100000,
                    require: 'coverage/blanket',
                    quiet: false, // Optionally suppress output to standard out (defaults to false)
                    clearRequireCache: true, // Optionally clear the require cache before running tests (defaults to false)
                },
                src: ['src/main/stuff/**/tests/*.spec.js']
            },
            coverage: {
                options: {
                    reporter: 'html-cov',
                    quiet: false,
                    captureFile: 'coverage.html'
                },
                src: ['src/main/stuff/**/*.js']
            }
        }
`

It keeps throwing an error:

`grunt mochaTest
Running "mochaTest:test" (mochaTest) task
Warning: Cannot find module 'coverage/blanket' Use --force to continue.
`

What am I doing wrong, or are the docs missing a step?  Sorry, this is the only place I could think to ask this. 

Sorry, I have no idea why the spacing is all whacky like that.  The code formatter is less than smart.

**Comment by pghalliday** [comment]
Did you create the `coverage/blanket` file as documented?

TBH, I should update these docs to reference `istanbul` instead. `blanket` is not really maintained anymore.

**Comment by gabaum10** [comment]
I tried, but I could have very well have done something wrong.  I didn't quite get what the entirety of the file should look like.  Do you need anything else in the file other than the require of the blanket stuff?

**Comment by pghalliday** [comment]
I think it should contain exactly this:

```
var path = require('path');
var srcDir = path.join(__dirname, '..', 'src');

require('blanket')({
  // Only files that match the pattern will be instrumented
  pattern: srcDir
});
```

assuming your source is in `src`

I am noticing that the grunt config says:

```
          require: 'coverage/blanket'
```

It might need to be:

```
          require: './coverage/blanket'
```

**Comment by gabaum10** [comment]
I was able to get the blanket part to fire successfully.  It was a configuration problem on my end.  I wasn't able to get it totally working, but that's less important right now and is likely an issue with blanket itself.  It's not super high on my priority list at this point.  The tests are working and that's what matters!  I'll revisit soon when I have more time.  Thanks for the help!

**Comment by pghalliday** [comment]
no problem - I think i will update the readme to reference istanbul as I mentioned, it's a more active project but is a bit more involved to integrate in my experience (notice that I ported the coverage for this project to istanbul a little while ago)

**Comment by gabaum10** [comment]
Yeah I actually saw that when I was looking through the code earlier looking for examples.  It would be cool to have an example setup for that.
