### ISSUE TITLE
Assertion failure in async tests crashes grunt with Fatal error

### ISSUE THREAD

**Issue by Bartvds** [pghalliday/grunt-mocha-test#13]
I have some async tests in mocha (using BDD pattern and either expect.js or chai's expect) that crash grunt-mocha-test with a Fatal error. It happens in multiple reporter (list, spec and my own).

It is reproducible when you use the `done` parameter in an asynchronous scenario that has a failing assert in the callback. I tested using a setTimeout, process.nextTick and fs.readFile).

Command-line mocha reports/logs the failure as expected and finishes the suites properly but in grunt a Fatal error will show (in red) and make grunt exit hard:

```
Fatal error: expected true to equal false
```

I see a similar issue here: https://github.com/yaymukund/grunt-simple-mocha/issues/16, it seems grunt is overly aggressive in handling uncaughtException.

**Comment by NKumbha** [comment]
this was very helpful - thanks.

**Comment by pghalliday** [comment]
@nkumbha you're welcome :)
