### ISSUE TITLE
Mocha exploded after grunt update

### ISSUE THREAD

**Issue by lhtdesignde** [pghalliday/grunt-mocha-test#136]
Hey, 

i'm using the latest build (0.13.3) and was running on grunt 0.4.5. After updating grunt now to 1.0.3, Mocha just explodes with a "SyntaxError: .yml: Unexpected character '#' (1:0)". 
With the older grunt it worked all fine. Do you have any idea why it's breaking now?
my config:
```
    mochaTest: {
      test: {
        options: {
          reporter: 'nyan', // http://mochajs.org/#reporters
          require: ['babel-register', '<%= paths.src %>/javascripts/react/test/mochaSetup.js']
        },
        src: ['<%= paths.src %>/javascripts/**/*-test.js']
      }
    },
```

**Comment by pghalliday** [comment]
Sorry, I'm not aware of any YML processing that would lead to this

**Comment by bonesoul** [comment]
same here.

**Comment by lhtdesignde** [comment]
I finally came to the bottom of this: This error is caused by a yml file. In my webpack setup I have a yml loader. Also mocha needs a yml loader. So to fix this I installed `mocha-yaml-loader` and updated the config:
```
    mochaTest: {
      test: {
        options: {
          reporter: 'nyan',
          require: ['mocha-yaml-loader', '@babel/register', '<%= paths.src %>/javascripts/react/test/mochaSetup.js'],
          clearRequireCache: false
        },
        src: ['<%= paths.src %>/javascripts/**/*-test.js']
      }
    },
```

**Comment by pghalliday** [comment]
Awesome, thanks for the update :)
