### ISSUE TITLE
'mocha-junit-reporter' renderOption mochaFile path issue 

### ISSUE THREAD

**Issue by gopinath-subramanian** [pghalliday/grunt-mocha-test#141]
Hey i am trying to use mocha-junit-reporter with mocha test , how i can pass the reporter option mochFille path part of the mochTest, At the moment we can define only the reporter ? not the render option ?

 mochaTest: {
            test: {
                options: {
                    require: 'ts-node/register',
                    reporter: 'mocha-junit-reporter',
                },
                src: [test.ts'],
            }
        },

**Comment by gopinath-subramanian** [comment]
reports goes to default path './test-results.xml'

**Comment by gopinath-subramanian** [comment]
nvm  it works with reporterOptions 
mochaTest: {
test: {
options: {
require: 'ts-node/register',
reporter: 'mocha-junit-reporter',
reporterOptions: {
                        mochaFile: "reports/test.xml"
                    }
},
src: [test.ts'],
}
},

**Comment by gopinath-subramanian** [comment]
You can close this issue

**Comment by pghalliday** [comment]
ok no problem, thanks
