### ISSUE TITLE
Support other mocha args

### ISSUE THREAD

**Issue by panjiesw** [pghalliday/grunt-mocha-test#44]
Like `--harmony-generators` or `--debug`
This is for upcoming node 0.11 which supports generator function. Also for emerging [koa](https://github.com/koajs/koa) framework which make heavy use of generator. It'll be very helpful if we can do test from grunt-mocha-test with that, instead of cli command.

**Comment by azachar** [comment]
I have experience a problem with timeouts and I am looking for a solution. In debug mode timeouts doesn't make any senses. So how should I achieve this?

**Comment by pghalliday** [comment]
Have you tried setting the time out to 0? (Not at computer right now)
