### ISSUE TITLE
Idea: Add files option to clearRequireCache

### ISSUE THREAD

**Issue by thejameskyle** [pghalliday/grunt-mocha-test#69]
Rather than only accepting a boolean for `clearRequireCache`, I think it would be useful to accept a file glob. This would allow you to cache things that take a long time to setup for watch tasks.

For example my tests need jsdom so that jquery can function. I setup it up to run like this:

```js
// ./tests/setup/jsdom.js
var jsdom = require('jsdom').jsdom;

global.document = jsdom('<html><head><script></script></head><body></body></html>');
global.window = document.createWindow();
```

```js
// ./tests/setup/node.js
var chai = require('chai');
var sinon = require('sinon');
var sinonChai = require('sinon-chai');

chai.use(sinonChai);

// check if window has already been created, if not then require jsdom
if (!global.window) {      // <<<<
  require('./jsdom');      // <<<<
}                          // <<<<

// setup backbone/built file
var $ = require('jquery');
var Backbone = require('backbone');
Backbone.$ = $;
var Behavior = require('../../../.tmp/behavior');

// setup globals so test files don't need to require them
global.sinon = sinon;
global.expect = chai.expect;
global.Backbone = Backbone;
global.Behavior = Behavior;
```

On the initial mocha run it takes about 400-500ms, then each subsequent run takes about 90-100ms. Which makes it feel instantaneous.

If there was a file glob option for `clearRequireCache` it could be cleaner, and I think it'd be a useful feature.

The problem with this is of course that things can be cached between test runs, however that will just depend on people being smart about what they are caching.

**Comment by whitecolor** [comment]
It could be useful.

**Comment by thejameskyle** [comment]
Closing this as part of cleaning out old issues. Feel free to reopen this.
