### ISSUE TITLE
EventEmitter-Leak / "uncaughtException" Handling 

### ISSUE THREAD

**Issue by ryyppy** [pghalliday/grunt-mocha-test#90]
Hey guys, 
I recently had these EventEmitter-Leak problems whenever I tried to re-run my watched tests for more than 10 times, I got a strange error message ("possible EventEmitter memory leak detected") and then grunt doesn't watch my file changes anymore.

As far as I grasped the code (tasks/mocha-test.js), you manage "uncaughtException"-Handlers after each Mocha-Run by...
1. Remembering all already existing handlers ([Line 71](https://github.com/pghalliday/grunt-mocha-test/blob/9a59cbab4ef8c41d0ffb57b35eaf49682aab0c75/tasks/mocha-test.js#L71))
2. Removing all handlers with `process.removeAllListeners('uncaughtExceptions')` ([Line 72](https://github.com/pghalliday/grunt-mocha-test/blob/9a59cbab4ef8c41d0ffb57b35eaf49682aab0c75/tasks/mocha-test.js#L72))
3. Rebinding the existing handlers from step 1 back to process to keep the Grunt-Handler etc. in place ([Lines 73-76](https://github.com/pghalliday/grunt-mocha-test/blob/9a59cbab4ef8c41d0ffb57b35eaf49682aab0c75/tasks/mocha-test.js#L73-76))

I checked the count of `process.listeners("uncaughtException")` for each run and realized that the number is going up, although the listeners will be removed... so I moved the `removeAllListeners("...")` line (from step 2) to the `done()`-Callback of `capture()` at [line 96](https://github.com/pghalliday/grunt-mocha-test/blob/9a59cbab4ef8c41d0ffb57b35eaf49682aab0c75/tasks/mocha-test.js#L96) and now everything runs as expected. 

This mod fixed the leak-problem (at least in my case) and also kept the original Grunt listener in place.

Is this a valid thing to do, or did I miss something? 

I use ...
- mocha - 2.0.1
- grunt-cli v0.1.13
- grunt v0.4.5
- grunt-mocha-test 0.11.0

The EventEmitter bug occurs in both cases, as soon as I re-run either a clean or a failed test 10 times continuously in the same watch-session.

**Comment by davedoesdev** [comment]
There are two added each time round:

1. [`domainUncaughtExceptionClear`](https://github.com/nodejs/node/blob/646e5a471766e27e8317bb54d1fd1d2c72cffb69/lib/domain.js#L183)

2. [`uncaught`](https://github.com/mochajs/mocha/blob/master/lib/runner.js#L883)

**Comment by davedoesdev** [comment]
This works me:

```js
    var unmanageExceptions = function() {
      var names = process.listeners('uncaughtException').map(function (f) {
        return f.name;
      });
      uncaughtExceptionHandlers.forEach(function (f) {
        if (names.indexOf(f.name) < 0) {
          process.on.bind(process, 'uncaughtException');
        }
      });
    };
```

Can't use object equality because Mocha binds handlers thus creating new objects.

**Comment by pghalliday** [comment]
I have merged the suggested change, closing this issue. Feel free to reopen if the issue reappears. I didn't do much except ensure the tests are passing as I don't really use this plugin or grunt anymore, but this leak was a bit of a niggle :)
