### ISSUE TITLE
color option only work for first run with watch (spawn: false)

### ISSUE THREAD

**Issue by whitecolor** [pghalliday/grunt-mocha-test#96]
If run test using `grunt-contrib-watch` with `spawn: false` mocha's `color: true` only works for first run.

**Comment by pghalliday** [comment]
I don't recommend using `spawn: false` with `grunt-contrib-watch` as it can cause all sorts of problems due to the require cache not being cleared. I'm not sure why it would impact the color option though. Did you also set `clearRequireCache: true` for `grunt-mocha-test`?

**Comment by whitecolor** [comment]
Yes of cource `clearRequireCache: true` is set. Without it `spawn: false` won't work. I use it because of test start speed, tests start at once, its importand for my BDD workflow,  without this option I have to wait a least several seconds before tests start after change, I don't likte this.

**Comment by whitecolor** [comment]
it seem to be the problem of my internal IDE console

**Comment by pghalliday** [comment]
ok thanks for closing
