### ISSUE TITLE
Multiple sections to organize tests

### ISSUE THREAD

**Issue by jrock2004** [pghalliday/grunt-mocha-test#97]
I would like to try to setup to have something where I could run grunt checkout or grunt my account and based of that run certain tests. This is what I have so far but it does not work. Is this something possible to do?

``` javascript
mochaTest: {
    cartandcheckout: {
        test: {
	    options: {
	        reporter: 'json',
	        captureFile: 'results/testResults.json',
	        quiet: false
	    },
	    src: ['test/cartandcheckout/*.js']
        }
      }
    }
```

**Comment by pghalliday** [comment]
the extra `test` object is not required, `options` and `src` should be specified directly under `cartandcheckout`

**Comment by pghalliday** [comment]
Been a few days now, hope that resolved your issue. Closing
