### ISSUE TITLE
mock-fs (filesystem mock) breaks test-run with exit code 0

### ISSUE THREAD

**Issue by neilmanuell** [pghalliday/grunt-mocha-test#99]
I assume that mocking the file system scrambles grunt-mocha-test's own use of the fs?
The test run successfully until the first mockFS is created then exits with code 0.
are there any existing strategies for this that you have come across

cheers

**Comment by pghalliday** [comment]
I don't know why this would be a problem so I would need to create a test case. Perhaps you could point me to an example of what you're trying to do?

**Comment by neilmanuell** [comment]
Thanks,

The activity of striping down the project to the bare essentials to replicate this brought to light the problem.

I actually had the captureFile set, which of cause was using the fs that was mocked and causing the runner to exit.

cheers

**Comment by pghalliday** [comment]
Ah, thanks for following up and closing :)
